---
ant_version: 1.10.1

jenkins_data: "/home/jenkins"
jenkins_home: "/var/lib/jenkins"
jenkins_tools: "{{jenkins_data}}/tools"
ant_base: "/opt"
ant_name: "apache-ant-{{ant_version}}"
ant_tarfile: "{{ant_name}}-bin.tar.gz"
ant_url: http://apache.cs.uu.nl//ant/binaries/{{ant_tarfile}}
