---

perl_rpms:
  - perl-Module-CoreList
  - perl-Module-Build
  - perl-Module-Info
  - perl-Module-Install
  - perl-CPAN
  - perl-Perl-Critic
  - perl-Test-Perl-Critic
  - perl-Test-Harness
  - perl-Test-Unit
  - perl-PDL
  - perl-Statistics-Descriptive
  - perl-Term-ReadLine-Gnu
  - perl-TermReadKey
  - perl-DBD-Pg
  - perl-DBD-MySQL
  - perl-Digest-Perl-MD5
  - perl-Digest-SHA
  - perl-Expect
  - perl-HTML-Parser
  - perl-HTML-Tidy
  - perl-LDAP
  - perl-Mail-Sendmail
  - perl-Redis
  - perl-TimeDate
  - perl-XML-Dumper
  - perl-YAML-LibYAML
  - perl-libwww-perl
  - postgresql-plperl