---
# This does not run in Daemon mode yet

- name: download swarm client
  environment: proxy_env
  get_url: url=http://maven.jenkins-ci.org/content/repositories/releases/org/jenkins-ci/plugins/swarm-client/{{ swarm_client_version }}/swarm-client-{{ swarm_client_version }}-jar-with-dependencies.jar
           dest=/tmp/swarm-client.jar

- name: run swarm client
  script: run_swarm_client.sh "{{ swarm_executors }}" "{{ swarm_master }}" "{{ inventory_hostname }}"
