---

- name: Creates directory
  win_file: path=c:/jenkins state=directory

- name: download swarm client
  environment: proxy_env
  win_get_url: url=http://maven.jenkins-ci.org/content/repositories/releases/org/jenkins-ci/plugins/swarm-client/{{ swarm_client_version }}/swarm-client-{{ swarm_client_version }}-jar-with-dependencies.jar dest=c:/jenkins/swarm-client.jar

- name: run swarm client
  script: run_swarm_client.ps1 "{{ swarm_executors }}" "{{ swarm_master }}" "{{ inventory_hostname }}"
