mvn_master_password: you_need_to_set_this_in_your_secrets_file
mvn_repo_username: deployer
mvn_repo_password: encryptit

maven_version: 3.3.9
maven_name: "apache-maven-{{maven_version}}"
maven_tarfile: "{{maven_name}}-bin.tar.gz"
maven_url: http://ftp.tudelft.nl/apache/maven/maven-3/{{maven_version}}/binaries/{{maven_tarfile}}
maven_location: '/opt/maven'
maven_home: "{{ maven_location }}/{{ maven_name }}"

mavenprofilename: profile
maven_mirror_url: "https://dev/artifactory/repo"
maven_snapshots_url: https://dev/artifactory/libs-snapshot
maven_releases_url: https://dev/artifactory/libs-release
