---
galaxy_info:
  author: Bas Meijer
  description: Prepares a Centos box by Hashicorp for Virtualbox
  company:
  license: license (BSD, MIT)
  min_ansible_version: 1.8
  platforms:
  - name: EL
    versions:
  #  - all
  #  - 5
    - 6
  #  - 7
  #- name: GenericUNIX
  #  versions:
  #  - all
  #  - any
  #- name: Fedora
  #  versions:
  #  - all
  #  - 16
  #  - 17
  #  - 18
  #  - 19
  #  - 20
  #- name: Amazon
  #  versions:
  #  - all
  #  - 2013.03
  #  - 2013.09
  #- name: SLES
  #  versions:
  #  - all
  #  - 10SP3
  #  - 10SP4
  #  - 11
  #  - 11SP1
  #  - 11SP2
  #  - 11SP3
  # Below are all categories currently available. Just as with
  # the platforms above, uncomment those that apply to your role.
  #
  categories:
  #- cloud
  - development
  - packaging
  - system
dependencies: []
  # List your role dependencies here, one per line. Only
  # dependencies available via galaxy should be listed here.
  # Be sure to remove the '[]' above if you add dependencies
  # to this list.

