---
- name: Download selenium on 'master' if we don't have it
  connection: local
  sudo: False
  environment: proxy_env
  get_url: url={{download_url}}  dest={{cur_dir}}/{{jar_file}} force=no

- name: Verify integrity of downloaded file
  connection: local
  sudo: False
  command: unzip -qt {{cur_dir}}/{{jar_file}}

- name: Copy selenium into place
  sudo: True
  copy: src={{jar_file}}  dest={{ selenium_dir }}/selenium-server.jar owner=root group=root mode=644

- name: Install Config
  sudo: True
  template: src=defaults.j2 dest=/etc/default/se_{{sel_role}} owner=root group=root mode=644
  tags: ['config']
  notify: selenium_restarted

- name: Install service file
  sudo: True
  template: src=redhat_init.j2 dest=/etc/init.d/se_{{sel_role}} owner=root group=root mode=755
  tags: ['config']
  notify: selenium_restarted

- name: Enable service
  sudo: True
  service: name=se_{{sel_role}} enabled=yes state=started

- name: Install browser
  sudo: True
  yum: name={{item}}
  with_items:
    - xorg-x11-server-Xvfb
    - firefox
  when:  sel_role != 'hub'
