---

- name: "make sure ca-certificates is latest"
  yum: name=ca-certificates state=latest
  tags:
    - httpd
    - ssl

- name: 'copy RootCA.cer to webserver'
  copy: src=files/certs/RootCA.cer dest=/var/www/html/RootCA.cer owner=apache group=apache mode=0644
  tags:
    - httpd
    - ssl

- name: "copy RootCA root cert"
  command: cp /var/www/html/RootCA.cer /etc/pki/ca-trust/source/anchors creates=/etc/pki/ca-trust/source/anchors
  tags:
    - httpd
    - ssl

- name: "enable ca-trust"
  command: update-ca-trust force-enable
  tags:
    - httpd
    - ssl

- name: "import RootCA root cert into Linux ca-trust"
  command: update-ca-trust extract
  tags:
    - httpd
    - ssl

- name: 'generate buildserver key'
  command: "openssl genrsa -out /etc/pki/tls/private/{{inventory_hostname}}.key 1024 creates=/etc/pki/tls/private/{{inventory_hostname}}.key"
  tags:
    - httpd
    - ssl

- name: 'generate certificate signing request'
  command: "openssl req -new -key /etc/pki/tls/private/{{inventory_hostname}}.key -out {{inventory_hostname}}.csr -subj '/C=AA/ST=NN/L=Ansible/O=localhost/CN={{inventory_hostname}}'"
  tags:
    - httpd
    - ssl

- name: 'fetch certficate signing request'
  fetch: src={{inventory_hostname}}.csr dest=files/certrequests/{{inventory_hostname}}.csr flat=yes
  tags:
    - httpd
    - ssl

- name: 'CA-sign buildserver key in a way to avoid https://github.com/mitchellh/vagrant/issues/2646'
  become: no
  local_action: shell /bin/bash --login -c 'openssl x509 -req -in files/certrequests/{{inventory_hostname}}.csr -CA files/certs/RootCA.pem -CAkey files/private/RootCA.key -CAcreateserial -out files/certs/{{inventory_hostname}}.cer -days 1800'
  args:
    creates: "files/certs/{{inventory_hostname}}.cer"
  tags:
    - httpd
    - ssl

- name: 'concatenate dh_parameters.txt to certificate'
  become: no
  local_action: "shell cat files/dh_parameters.txt >> files/certs/{{inventory_hostname}}.cer"
  notify:
    - restart httpd
  tags:
    - httpd
    - ssl

- name: 'copy certificate to webserver'
  copy: src=files/certs/{{inventory_hostname}}.cer dest=/etc/pki/tls/certs/{{inventory_hostname}}.cer
  tags:
    - httpd
    - ssl


