---
features:
  ant: True
  maven: True
  gradle: False
  system_auth: False

ant_version: 1.9.4
maven_version: 3.2.5
gradle_version: 2.2.1
java_home: /usr/lib/jvm/java

plugins:
  - 'analysis-collector'
  - 'analysis-core'    # for findbugs
  - 'artifactory'      # connect to build repository
  - 'checkstyle'       # source code formatting reports
  - 'cobertura'
  - 'dashboard-view'
#  - 'dry'              # don't repeat yourself
  - 'findbugs'          # common bugs can be squashed
  - 'fortify360'
  - 'git'              # connect to git
  - 'gradle'           # build tool
  - 'jacoco'           # test coverage
  - 'jira'             # Atlassian Jira API
  - 'jobConfigHistory' # save changes in job configuration
  - 'junit'
  - 'ldap'
  - 'mailer'
  - 'pmd'              #
  - 'release'
  - 'role-strategy'
  - 'ssh-agent' 
  - 'sonar'            # source code quality
#  - 'thinBackup'       # backup job configurations
#  - 'violations'       #
  
jenkins_base_url: 'http://pkg.jenkins-ci.org/redhat'
jenkins_data: "/data/jenkins"
jenkins_home: "/var/lib/jenkins"
jenkins_tools: "{{jenkins_data}}/tools"
jenkins_https: 8443
jenkins_cli: '{{ jenkins_data }}/jenkins-cli.jar' # Jenkins CLI executable
updates_dest: '{{ jenkins_data }}/updates_jenkins.json' # Jenkins updates
jenkins_repo: "jenkins.repo"
jenkins_repo_key: "{{jenkins_base_url}}/jenkins-ci.org.key"
jenkins_phrase: "ask_devops"

rpm_dependencies:
  - 'java-1.7.0-openjdk'
  - 'java-1.7.0-openjdk-devel'
  - 'jenkins'
  - 'curl'
  - 'unzip'


maven_name: "apache-maven-{{maven_version}}"
maven_tarfile: "{{maven_name}}-bin.tar.gz"
maven_url: http://ftp.nluug.nl/internet/apache/maven/maven-3/{{maven_version}}/binaries/{{maven_tarfile}}
maven_home: "{{jenkins_tools}}/hudson.tasks.Maven_MavenInstallation/{{maven_name}}"

ant_name: "apache-ant-{{ant_version}}"
ant_tarfile: "{{ant_name}}-bin.tar.gz"
ant_url: http://ftp.tudelft.nl/apache/ant/binaries/{{ant_tarfile}}
ant_home: "{{jenkins_tools}}/hudson.tasks.Ant_AntInstallation/{{ant_name}}"

gradle_name: "gradle-{{gradle_version}}"
gradle_zipfile: "{{gradle_name}}-all.zip"
gradle_url: https://services.gradle.org/distributions/{{gradle_zipfile}}
gradle_home: "{{jenkins_tools}}/hudson.plugins.gradle.GradleInstallation/{{gradle_name}}"

jenkins_configs:
  - 'config.xml'
  - 'hudson.maven.MavenModuleSet.xml'
  - 'hudson.model.UpdateCenter.xml'
  - 'hudson.plugins.analysis.core.GlobalSettings.xml'
  - 'hudson.plugins.git.GitSCM.xml'
  - 'hudson.plugins.git.GitTool.xml'
  - 'hudson.plugins.gradle.Gradle.xml'
  - 'hudson.plugins.jira.JiraProjectProperty.xml'
  - 'hudson.plugins.sonar.SonarPublisher.xml'
  - 'hudson.plugins.sonar.SonarRunnerInstallation.xml'
  - 'hudson.scm.CVSSCM.xml'
  - 'hudson.scm.SubversionSCM.xml'
  - 'hudson.tasks.Ant.xml'
  - 'hudson.tasks.Mailer.xml'
  - 'hudson.tasks.Maven.xml'
  - 'hudson.tasks.Shell.xml'
  - 'hudson.triggers.SCMTrigger.xml'
  - 'jenkins.model.ArtifactManagerConfiguration.xml'
  - 'jenkins.model.DownloadSettings.xml'
  - 'jenkins.model.JenkinsLocationConfiguration.xml'
  - 'jenkins.mvn.GlobalMavenConfig.xml'
  - 'jobConfigHistory.xml'
  - 'nodeMonitors.xml'
  - 'org.jenkinsci.plugins.gitclient.JGitTool.xml'
  - 'org.jfrog.hudson.ArtifactoryBuilder.xml'
  - 'org.jvnet.hudson.plugins.fortify360.FPRPublisher.xml'
  - 'sonar.xml'


