---
features:
  mysql: True
  postgresql: False

sonar_username: 'sonar'
sonar_password: 'PGKaeE3Xhp2B1'

sonar_repo: 'http://downloads.sourceforge.net/project/sonar-pkg/rpm/sonar.repo'
sonarrunner_zipfile: 'sonar-runner-dist-2.4.zip'
sonarrunner_url: 'http://repo1.maven.org/maven2/org/codehaus/sonar/runner/sonar-runner-dist/2.4/sonar-runner-dist-2.4.zip'

sonar_dependencies:
  - 'java-1.7.0-openjdk'
  - 'sonar-4.5'

sonar_plugins:
# Integration
  - 'http://repository.codehaus.org/org/codehaus/sonar-plugins/sonar-ldap-plugin/1.4/sonar-ldap-plugin-1.4.jar'
  - 'http://repository.codehaus.org/org/codehaus/sonar-plugins/sonar-jira-plugin/1.2/sonar-jira-plugin-1.2.jar'  
# Platforms
  - 'http://repository.codehaus.org/org/codehaus/sonar-plugins/java/sonar-java-plugin/2.5.1/sonar-java-plugin-2.5.1.jar'
  - 'http://repository.codehaus.org/org/codehaus/sonar-plugins/javascript/sonar-javascript-plugin/2.2/sonar-javascript-plugin-2.2.jar'
  - 'http://repository.codehaus.org/org/codehaus/sonar-plugins/python/sonar-python-plugin/1.3/sonar-python-plugin-1.3.jar'
  - 'http://repository.codehaus.org/org/codehaus/sonar-plugins/xml/sonar-xml-plugin/1.2/sonar-xml-plugin-1.2.jar'
  - 'http://repository.codehaus.org/org/codehaus/sonar-plugins/android/sonar-android-plugin/1.0/sonar-android-plugin-1.0.jar'
# Analysis
  # picky on versions
  - 'http://repository.codehaus.org/org/codehaus/sonar-plugins/java/sonar-checkstyle-plugin/2.1.1/sonar-checkstyle-plugin-2.1.1.jar'
  - 'http://repository.codehaus.org/org/codehaus/sonar-plugins/sonar-cobertura-plugin/1.6.3/sonar-cobertura-plugin-1.6.3.jar'
  - 'http://repository.codehaus.org/org/codehaus/sonar-plugins/java/sonar-findbugs-plugin/3.1/sonar-findbugs-plugin-3.1.jar'

# C++ € 7,000
#  - 'http://repository.codehaus.org/org/codehaus/sonar-plugins/sonar-cpp-plugin/3.2/sonar-cpp-plugin-3.2.jar'
# PL/SQL € 3,200
#  - 'http://repository.codehaus.org/org/codehaus/sonar-plugins/sonar-plsql-plugin/2.6/sonar-plsql-plugin-2.6.jar'
# Fortify requires separate license for Fortify
#  - 'http://repository.codehaus.org/org/codehaus/sonar-plugins/sonar-fortify-plugin/2.0/sonar-fortify-plugin-2.0.jar'

# Reporting
  - 'http://repository.codehaus.org/org/codehaus/sonar-plugins/sonar-build-breaker-plugin/1.1/sonar-build-breaker-plugin-1.1.jar'
#  - 'http://repository.codehaus.org/org/codehaus/sonar-plugins/jmeter/sonar-jmeter-plugin/0.2/sonar-jmeter-plugin-0.2.jar'
  - 'http://repository.codehaus.org/org/codehaus/sonar-plugins/sonar-motion-chart-plugin/1.7/sonar-motion-chart-plugin-1.7.jar'
 # - 'http://repository.codehaus.org/org/codehaus/sonar-plugins/sonar-quality-index-plugin/1.1.3/sonar-quality-index-plugin-1.1.3.jar'
  - 'http://repository.codehaus.org/org/codehaus/sonar-plugins/sonar-technicaldebt-plugin/1.2.1/sonar-technicaldebt-plugin-1.2.1.jar'
  - 'http://repository.codehaus.org/org/codehaus/sonar-plugins/sonar-timeline-plugin/1.4/sonar-timeline-plugin-1.4.jar'
#  - 'http://repository.codehaus.org/org/codehaus/sonar-plugins/sonar-useless-code-tracker-plugin/1.0/sonar-useless-code-tracker-plugin-1.0.jar'

